pull_request_rules:
  - name: automatic merge
    conditions:
      - check-success=Build
      - label=auto-merge
      - label!=auto-squash-merge
      - base=master
    actions:
      merge:
        method: merge
  - name: automatic squash merge
    conditions:
      - check-success=Build
      - label=auto-merge
      - label=auto-squash-merge
      - base=master
    actions:
      merge:
        method: squash
  - name: branch deletion after merge
    conditions:
      - merged
      - label=auto-delete-branch
    actions:
      delete_head_branch: {}
